import Head from "next/head";

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<Head>
				<title>Basic Multitenant</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<body className="bg-gradient-to-b from-sky-200 to-blue-200">
				<h1 className="text-6xl font-bold text-center">Under Subdomain</h1>
				{children}
			</body>
		</html>
	);
}
